name-template: 'B_v$NEXT_PATCH_VERSION'
tag-template: 'B_v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature-B'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix-B'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'exclude-ReleaseNote'
  - 'feature-A'
  - 'fix-A'
template: |
  # Changes

  $CHANGES
