name: if
inputs:
  service:
    type: string
    required: true

outputs:
  text:
    value: ${{ steps.p.outputs.TEXT }}

runs:
  using: composite
  steps:
    - name: a
      if: inputs.service == 'a'
      shell: bash
      run: echo "TEXT='a run'" >> $GITHUB_ENV
    - name: b
      if: inputs.service == 'b'
      shell: bash
      run: echo "TEXT='b run'" >> $GITHUB_ENV
    - name: c
      if: inputs.service == 'c'
      shell: bash
      run: echo "TEXT='c run'" >> $GITHUB_ENV
    - if: ${{ ! failure() }}
      id: p
      shell: bash
      run: echo "TEXT=$TEXT" >> $GITHUB_OUTPUT
