name: aws-credential-split
on:
  workflow_dispatch

jobs:
  credential:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Configure AWS Credentials
        uses: ./.github/actions/aws-login
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      -
        name: a
        run: aws sts get-caller-identity
