name: aws-credential-split
on:
  push:
    branches:
      - master
jobs:
  credential:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      -
        name: a
        run: aws sts get-caller-identity
  cli:
    runs-on: ubuntu-latest
    needs: credential
    steps:
      - run: aws sts get-caller-identity
