name: if
on: [push]
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo A
  B:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  C:
    needs: [A, B]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - run: echo ${{ env.WORKFLOW_CONCLUSION }}
