name: docker cache
on:
  pull_request:
    branches:
      - master
jobs:
  build_a:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: cache-builder-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            cache-server-${{ github.ref }}-${{ github.sha }}
            cache-builder-${{ github.ref }}-
            cache-server-${{ github.ref }}-
            cache-builder-
            cache-server-
      -
        name: Build(a)
        uses: docker/build-push-action@v4
        with:
          context: example/docker-cache/
          file: example/docker-cache/Dockerfile
          target: builder
          tags: sample-builder:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build_b:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: cache-server-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            cache-builder-${{ github.ref }}-${{ github.sha }}
            cache-server-${{ github.ref }}-
            cache-builder-${{ github.ref }}-
            cache-server-
            cache-builder-
      -
        name: Build(a)
        uses: docker/build-push-action@v4
        with:
          context: example/docker-cache/
          file: example/docker-cache/Dockerfile
          target: server
          tags: sample-server:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache