name: example

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Validate Branch Name
        run: |
          if [[ $GITHUB_REF =~ ^refs/heads/v.* ]]; then
            echo "::error::Invalid branch name. A branch name must not start with 'v'."
            exit 1
          elif [[ $GITHUB_REF =~ ^refs/heads/staging_.* ]]; then
            echo "::error::Invalid branch name. A branch name must not start with 'staging_'."
            exit 1
          elif [[ ${#GITHUB_REF} -gt 63 ]]; then
            echo "::error::Invalid branch name. The name must be less than 64 characters."
            exit 1
          fi
