name: example

on: [push]

jobs:
  test:
    env:
      RELEASE_REPOSITORY_URI: aaaa
      SNAPSHOT_REPOSITORY_URI: bbbb
      target: RELEASE
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.ref }}
      - run: echo $(eval echo "REPOSITORY_URI1=\${${target^^}_REPOSITORY_URI}") >> $GITHUB_ENV
      - run: echo "$(eval echo REPOSITORY_URI2=\${${target^^}_REPOSITORY_URI})" >> $GITHUB_ENV
      - run: env
