name: example with space

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      notify_type:
        description: a
        required: true
        type: choice
        options: [notice, start]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        run: echo
          ${{ github.event.inputs.notify_type }}
          $HOGE
        env:
          HOGE: $(ls)
      -
        id: created_at
        run: echo "value=$(TZ=UTC-9 date '+%Y/%m/%d %H:%M:%S')" >> $GITHUB_OUTPUT
      -
        run: echo $CREATED_AT
        env:
          CREATED_AT: ${{ steps.created_at.outputs.value }}
