name: example

on: [push]

jobs:
  test:
    env:
      RELEASE_REPOSITORY_URI: aaaa
      SNAPSHOT_REPOSITORY_URI: bbbb
      target: release
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sun-yryr/discordbot-sample
          tags: |
            type=semver,pattern={{version}},value=0.1.0
