name: example

on:
  push:
    branches:
      - "master"

env:
  image_uri: ${{ secrets.AWS_ECR_REPO_NAME }}:dev-${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp symfony
        uses: ./.github/actions/symfony-setup
      - name: PHPUnit
        run: echo "phpunit"
