name: example

on:
  push:
    branches:
      - "master"
jobs:
  test:
    uses: sun-yryr/github-actions-playground/.github/workflows/reusable-workflow.yml@master
    with:
      workspace: "example"
