name: expression ternary operator
on:
  workflow_dispatch:
    inputs:
      input1:
        type: string
        required: true

env:
  sample1: ${{ inputs.input1 == 'allow' && 'OK' || 'NG' }}
  sample2:
    ${{
      inputs.input1 == 'allow' &&
        'OK' ||
        'NG'
    }}
  sample3: |
    ${{
      inputs.input1 == 'allow' &&
        'OK' ||
        'NG'
    }}
  sample4: |-
    ${{
      inputs.input1 == 'allow' &&
        'OK' ||
        'NG'
    }}


jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      -
        run: echo '<${{ env.sample1 }}>'
      -
        run: echo '<${{ env.sample2 }}>'
      -
        run: echo '<${{ env.sample3 }}>'
      -
        run: echo '<${{ env.sample4 }}>'
