name: interaction-between-branches
on: push

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/save@v3
        with:
          path: output.txt
          key: main
      - run: cat output.txt
  save:
    runs-on: ubuntu-latest
    needs:
      - restore
    if: failure()
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.sha }} > output.txt
      - uses: actions/cache/save@v3
        with:
          path: output.tx
          key: main
