name: artifact marker based deduplication(reusable)

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

concurrency:
  # PRの場合はブランチごとにグループ化して古いものをキャンセルする
  # それ以外の場合はコミットハッシュでグループ化する
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

env:
  MARKER_NAME: deduplication-success-${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - run: |
          gh api \
              "/repos/${REPO}/actions/artifacts?name=${MARKER_NAME}"
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}

  check-marker:
    runs-on: ubuntu-slim
    outputs:
      exists: ${{ steps.marker.outputs.exists }}
    steps:
      - name: Check exists marker
        id: marker
        run: |
          found=$(gh api \
            "/repos/${REPO}/actions/artifacts?name=${MARKER_NAME}" \
            --jq '.total_count')
          
          if [ "$found" -gt 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}

  process:
    needs: [check-marker]
    if: ${{ needs.check-marker.outputs.exists != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo 'a'

  save-success-marker:
    needs: [process]
    runs-on: ubuntu-slim
    steps:
      - name: Create marker
        run: echo "${GITHUB_SHA}" > marker.txt

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.MARKER_NAME }}
          path: marker.txt
