name: object matrix
on:
  push:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.a.outputs.test }}
    steps:
      - name: Prepare
        id: a
        run: echo '[{"name":"@xx/xx","version":"1.2.0"},{"name":"@xx/xy","version":"0.8.9"}]' >> "$GITHUB_OUTPUT"
  matrix:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: ${{ needs.prepare.outputs.test }}
    steps:
      - name: Test
        run: |
          echo '${{ matrix.name }}'
          echo '${{ matrix.version }}'
