name: on-release-tag

on:
  release:
    types: [ released ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo EventName $GITHUB_EVENT_NAME
      - run: echo $GITHUB_REF | sed -e 's/refs\/tags\///'