name: Renovate
on:
  push:
    branches:
      - "master"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.158.1
        with:
          configurationFile: example/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}