name: reusable
on:
  workflow_call:

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo A
  B:
    runs-on: ubuntu-latest
    steps:
      - run: echo B
  C:
    runs-on: ubuntu-latest
    if: github.ref_name == 'stg'
    steps:
      - run: echo C
