name: show-github
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - released
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
