name: Use reusable workflow
on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo prepare
  reuse:
    needs: [prepare]
    uses: ./.github/workflows/reusable-workflow.yml
  status:
    needs: [reuse]
    runs-on: ubuntu-latest
    steps:
      -
        run: echo ${{ needs.reuse.result }}
  skip:
    needs: [status]
    if: github.ref_name == ''
    runs-on: ubuntu-latest
    steps:
      - run: echo a
  a:
    needs: [skip]
    runs-on: ubuntu-latest
    steps:
      - run: echo a
  b:
    needs: [a]
    if: ${{ ! failure() && needs.a.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo b
  c:
    needs: [a]
    if: ${{ ! failure() && needs.a.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo c
